# Generated by Django 6.0 on 2025-12-27 00:18

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('default_location', models.CharField(blank=True, max_length=300)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('start_date', models.DateField(help_text='First date the series can occur on')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date', null=True)),
                ('start_time', models.TimeField(help_text='Start time for each occurrence')),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Mon ... 6=Sun. Used for weekly/biweekly schedules.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='events.eventcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Denver', max_length=64)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True)),
                ('registration_url', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members'), ('private', 'Private')], db_index=True, default='private', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_registration', models.BooleanField(default=False, help_text='Check if attendees must register to attend.')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Last date/time attendees can register', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
                ('series', models.ForeignKey(blank=True, help_text='If set, this event is an occurence generated from a series', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventseries')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['status', 'start'], name='events_even_status_336136_idx'), models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx')],
            },
        ),
    ]
