# Generated by Django 6.0 on 2025-12-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='week_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1=first, 2=second, 3=third, 4=fourth, 5=last', null=True),
        ),
    ]
