# Generated by Django 6.0 on 2025-12-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventseries_week_of_month'),
        ('extras', '0002_imageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='extras.imageattachment'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series', to='extras.imageattachment'),
        ),
    ]
