# Generated by Django 6.0 on 2025-12-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_eventseries_image'),
        ('extras', '0002_imageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='extras.imageattachment'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series', to='extras.imageattachment'),
        ),
    ]
