# Generated by Django 6.0 on 2026-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image_alter_eventseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseries',
            name='week_of_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Last')], help_text='1=first, 2=second, 3=third, 4=fourth, 5=last', null=True),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun', null=True),
        ),
    ]
