# Generated by Django 6.0 on 2026-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventseries_week_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
