# Generated by Django 6.0 on 2026-01-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventseries_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='default_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
