# Generated by Django 6.0 on 2026-01-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventseries_default_address'),
        ('extras', '0002_imageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='extras.imageattachment'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series', to='extras.imageattachment'),
        ),
    ]
