# Generated by Django 6.0 on 2026-01-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_image_alter_eventseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, help_text='If set, this event is an occurence generated from a series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventseries'),
        ),
    ]
