# Generated by Django 6.0 on 2026-01-27 04:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
