# Generated by Django 6.0 on 2026-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesttag',
            name='group',
            field=models.CharField(choices=[('interview', 'Interview'), ('programs', 'Programs'), ('connect', 'Connect'), ('learn', 'Learn More')], default='connect', max_length=80),
        ),
    ]
